name: Build typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: main.typ

      - name: Rename PDF file
        run: mv main.pdf portugues_em_foco_3.pdf

      #- name: Upload PDF file
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: PDF
      #    path: portugues_em_foco_3.pdf
      #    overwrite: true

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: portugues_em_foco_3.pdf

      - name: Keep last 2 releases
        uses: sgpublic/delete-release-action@v1.2
        with:
          # repo: '<owner>/<repoName>' # you can input a another repo here, defaults to current repo
          release-drop: true
          release-keep-count: 1
          release-drop-tag: true
          pre-release-drop: true
          pre-release-keep-count: 1
          pre-release-drop-tag: true
          draft-drop: true
          draft-drop-count: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
